version: 1
formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: .bitcoin_safe.log
    maxBytes: 10485760  # 10 MB (adjust the size as needed)
    backupCount: 0     # Number of backup files to keep
loggers:
  root:
    level: DEBUG
    handlers: [console, file]
    propagate: no
