#
# Bitcoin Safe
# Copyright (C) 2026 Andreas Griffin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of version 3 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/gpl-3.0.html
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

from pathlib import Path
import os


def is_vscode_server_container() -> bool:
    return Path("/.dockerenv").exists() and bool(os.environ.get("VSCODE_IPC_HOOK_CLI"))


def build_env_lines() -> list[str]:
    lines = [
        "# Auto-generated by tools/write_vscode_env.py.",
        "# This file is intentionally minimal so local launches keep their default environment.",
    ]
    if is_vscode_server_container():
        lines.extend(
            [
                "DISPLAY=desktop:0",
                "QT_QPA_PLATFORM=xcb",
            ]
        )
    return lines


def main() -> None:
    workspace = Path(__file__).resolve().parent.parent
    env_file = workspace / ".vscode" / ".env.launch"
    env_file.write_text("\n".join(build_env_lines()) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
