#
# Bitcoin Safe
# Copyright (C) 2026 Andreas Griffin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of version 3 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/gpl-3.0.html
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

from __future__ import annotations

import ipaddress
import json
import logging
from dataclasses import dataclass
from pathlib import Path

from bitcoin_safe.util import resource_path

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class GeoLocation:
    latitude: float
    longitude: float
    country_code: str | None = None


class RoughGeoIpDatabase:
    """Look up rough geo coordinates for IP addresses.

    The backing JSON file is expected to be generated by
    `tools/download_rough_geoip_db.py`.
    """

    def __init__(self, db_path: Path | None = None) -> None:
        self.db_path = db_path or Path(resource_path("data", "geoip_rough_v1.json"))
        self._loaded = False
        self._ipv4_prefix = 12
        self._ipv6_prefix = 32
        self._ipv4_map: dict[int, GeoLocation] = {}
        self._ipv6_map: dict[int, GeoLocation] = {}

    def _load(self) -> None:
        if self._loaded:
            return

        self._loaded = True
        if not self.db_path.exists():
            logger.info("GeoIP rough database not found at %s", self.db_path)
            return

        try:
            payload = json.loads(self.db_path.read_text(encoding="utf-8"))
        except Exception:
            logger.exception("Failed reading GeoIP rough database from %s", self.db_path)
            return

        prefix_lengths = payload.get("prefix_lengths", {})
        self._ipv4_prefix = int(prefix_lengths.get("ipv4", 12))
        self._ipv6_prefix = int(prefix_lengths.get("ipv6", 32))

        self._ipv4_map = self._decode_map(payload.get("ipv4", {}))
        self._ipv6_map = self._decode_map(payload.get("ipv6", {}))

    @staticmethod
    def _decode_map(data: dict[str, list[object]]) -> dict[int, GeoLocation]:
        mapped: dict[int, GeoLocation] = {}
        for key_str, value in data.items():
            if len(value) < 2:
                continue

            raw_latitude = value[0]
            raw_longitude = value[1]
            if not isinstance(raw_latitude, int | float | str):
                continue
            if not isinstance(raw_longitude, int | float | str):
                continue

            try:
                key = int(key_str)
                latitude = float(raw_latitude)
                longitude = float(raw_longitude)
            except Exception:
                continue

            country_code: str | None = None
            if len(value) >= 3 and isinstance(value[2], str):
                country_code = value[2]

            mapped[key] = GeoLocation(latitude=latitude, longitude=longitude, country_code=country_code)

        return mapped

    def lookup_ip(self, ip: ipaddress.IPv4Address | ipaddress.IPv6Address) -> GeoLocation | None:
        self._load()

        if ip.version == 4:
            prefix_key = int(ip) >> (32 - self._ipv4_prefix)
            return self._ipv4_map.get(prefix_key)

        prefix_key = int(ip) >> (128 - self._ipv6_prefix)
        return self._ipv6_map.get(prefix_key)

    def lookup_host(self, host: str) -> GeoLocation | None:
        try:
            ip = ipaddress.ip_address(host)
        except ValueError:
            return None

        return self.lookup_ip(ip)
