name: Build MacOsX  dmg Arm64
on:
  workflow_dispatch:
    inputs:
      commitHash:
        description: 'Enter the commit hash to build (leave empty to use the default branch or the branch that triggered the workflow)'
        required: false
        type: string
      buildDMG:
        description: 'Test Build DMG (Arm64)'
        required: false
        type: boolean

  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14  # see available: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          ref: ${{ github.event.inputs.commitHash || github.sha }}


      - name: Run build script
        run: tools/build-mac/make_osx.sh 


      - name: Check for DMG file
        run: |
          if [ -z "$(find dist -type f -name '*.dmg')" ]; then
            echo "dmg file is missing"
            exit 1
          fi


      - name: Upload DMG Files from dist/
        uses: actions/upload-artifact@v4
        with:
          name: dmgs
          path: dist/*.dmg